use std::collections::HashMap;

fn main() {
    const NOTE : &str = "ABCABBBCCAACAABAABCACBBCBBCBBBBABCACAACCCCACACAABABACCBABACACACABBCBCACBCBCBCCACBACCBBCABACAACCBBACCAACAAACABAAACABBCBCCABCABCCAACBBCCAAAABBBBCBABACCCCCCCACACCABCAAAAAACACBBAABCABBBBAAAABCCABABBAACCBCCBABACACACABACACBCBCCCCAAABCCCCBCBBAABCCACCBAACCCBABAABAACBABACBCACBBCAACCCCBCBBAAABBCABABCBCAACCAACCABBAAABCBAACBACCAABBBACCABBCBBCABBACBBBCBBBBBAACCCCABBBBCABCABCCCCBBBAAABBBCBACACABACCABBABCBCAAACBCBBBBCABCCAAACCCCBABABCBABABBABBAABBABAABBAACBCBCABABCBACACACACCBCCABBBBAAABABBBBBABACCABACCBCBABACBBAAABCBBAAACABCABBBBCCABCACACCCABCAABBABCBAABCAAACCBCBABBBACACCABACAACCAACCCCBCBACCACAACCCACCBBBABBCABAABAAACBAACAABACCBABCCACACBAAAAABAACBACBABBAABABAAACBCBCBBBABBBBCBCCABCACCACBCBABCCBAACCAABAABCACBABACBACABCCCCBCBBABABABBBABCACCCCBCABBAABBCACABBCACCABBCCCCAACBBAABCBCBACABACCCBABAAABBBBCACAABCBCCCAAABBCACACBCBCBCCBCACCBAACBABBCAABAABBCBCABCBBACAACCCBCBABBACCACAAAACACABCCABBCBBBBBCACCCAACABACCCCACCBBACBCBCCACAABBBCCCABBBBBCBBCBAAABCBACABACABCAAACACCBCCCBBCAAAACABBCCBACCBCCBBBAACAACBACBCBABAACCC";
    let data = HashMap::from([("A", 0),("B", 1), ("C", 3)]);
    let mut total = 0;
    // iterate over the note
    for char in NOTE.chars() {
        // get the value of the character
        let letter = &char.to_string();
        let value = data.get(letter.as_str()).unwrap();
        // add the value to the total
        total += value;
    }

    println!("Total: {}", total);
}
